[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DNAVDASH_ENABLE_LCD=0
  -DNAVDASH_ENABLE_VIDEO=0
  -Ilib/h264bsd/src
  -DTFT_CS=15
  -DTFT_DC=2
  -DTFT_RST=-1
  -DTFT_BL=21
  -DTFT_MOSI=13
  -DTFT_MISO=12
  -DTFT_SCLK=14
